// lang.js
const translations = {
fr: {
    about: "à propos",
    intro: "Salut ! Je m'appelle Clara, je suis étudiante en développement web basée à Paris. Ce que j'aime, c'est mettre ma touche personnelle pour créer des sites web beaux et fonctionnels en front-end comme en back. Je suis toujours à la recherche d'opportunités pour apprendre et développer mes compétences. Je suis actuellement à la recherche d'une alternance en Déveoppemet Web à partir de septembre 2025. N'hésitez pas à me contacter si vous souhaitez collaborer!",
    cv: "Mon CV",
    analogie: "Pourquoi les développeurs détestent-ils la nature ?",
    responsive: "Parce qu’il y a trop de branches.",
    positions: "Réinitialiser les positions",
    projets: "Projets",
    opquast: "Je suis formée et certifiée (niveau expert) aux règles Opquast, qui concernent les bonnes pratiques pour la qualité web, depuis avril 2025.",
    opquast2: "Opquast m’aide à appliquer des bonnes pratiques de qualité web dans mes projets, en me concentrant sur des aspects comme l’accessibilité, la performance et l’ergonomie pour offrir une meilleure expérience utilisateur. Cela me permet de rendre les sites et applications que je crée plus faciles à utiliser, plus rapides et accessibles à un plus grand nombre de personnes, y compris les personnes en situation de handicap.",
    temoignages: "avis",
    aly: "''Ça fait presque deux ans qu'on travaille ensemble, et franchement, Clara est une vraie perle. Toujours pleine d’idées et d’énergie, elle est super impliquée dans ses projets et travaille de manière très efficace. Elle a un sens du détail incroyable et sait toujours trouver des solutions à des problèmes qu’on rencontre.''",
    emi: "''Clara est une personne très douée en développement web, elle apporte toujours sa touche personnelle et est vraiment investie en cours dans ses différents sites web. Ce qui fait toute sa singularité, c’est qu’elle tient beaucoup à ses travaux. C’est également un bon leader pour les projets en groupe.''",
    mel: "''Clara est une personne super investie. Je trouve qu’elle a une vraie capacité à apprendre vite et à s’adapter ce qui est plutôt important pour son avenir. Elle est à l’écoute et c’est quelqu’un avec qui on a plaisir à collaborer, que ce soit sur un projet ou dans une discussion plus large.''",
    contact: "Vous avez un projet en tête ou vous souhaitez simplement discuter ? N'hésitez pas à me contacter !",
    follow: "Suivez-moi",
    previous: "Projet précédent",
    next: "Projet suivant",
    baron: "Site TIM",
    aly_tobe: "Graphiste en devenir",
    emi_tobe: "Illustratrice en devenir",
    mel_tobe: "Développeuse web en devenir",
    dessins: "Tous les dessins présentés sur ce site sont réalisés par mes soins.",
},
en: {
    about: "About Me",
    intro: "Hi! I'm Clara, a web developer student based in Paris. I'm passionate about creating beautiful and functional websites, whether it is in front-end or back-end. I'm always looking for new opportunities to learn and develop my skills. I'm currently looking for an internship in Web Development, starting from September 2025. Feel free to contact me if you'd like to work together!",
    cv: "My CV",
    analogie: "Why was the developer broke?",
    responsive: "Because he used up all his cache.",
    positions: "Reset positions",
    projets: "Works",
    opquast: "I am trained and certified (expert level) in the Opquast rules, which focus on best practices for web quality, as of April 2025.",
    opquast2: "Opquast helps me apply good web quality practices in my projects by focusing on aspects such as accessibility, performance, and usability to provide a better user experience. This allows me to make the websites and applications I create easier to use, faster, and accessible to a broader audience, including people with disabilities.",
    temoignages: "reviews",
    aly: "''It’s been almost two years that we’ve been working together, and honestly, Clara is an absolute gem. Always full of ideas and energy, she’s very committed to her projects and works very efficiently. She has an incredible attention to detail and always finds solutions to the problems we face.''",
    emi: "''Clara is very talented in web development, always bringing her personal touch and being truly dedicated in class with her various web projects. What makes her unique is her strong commitment to her work. She’s also a great leader for group projects.''",
    mel: "''Clara is incredibly dedicated. I think she has a real ability to learn quickly and adapt, which is quite important for her future. She’s attentive and someone you genuinely enjoy collaborating with, whether on a project or in a broader conversation.''",
    contact: "You have a project in mind or just want to chat? Feel free to contact me!",
    follow: "Follow me",
    previous: "Previous project",
    next: "Next project",
    baron: "Tim Website",
    aly_tobe: "Future graphic designer",
    emi_tobe: "Future illustrator",
    mel_tobe: "Future web developer",
    dessins: "All the drawings presented on this website are made by me.",
},
};
